management:
  # only expose /health from actuator
  endpoints:
    enabled-by-default: false
    web:
      base-path: ''
      path-mapping:
        health: /health
  endpoint:
    health:
      enabled: true

  tracing:
    sampling:
      # tracing is triggered only if the client has enabled context propagation
      probability: 0.0
    propagation:
      type: w3c
  zipkin:
    tracing:
      endpoint: ${zipkin.baseUrl:http://127.0.0.1:9411}/api/v2/spans
spring:
  application:
    # this name will be used to tag spans sent to the Zipkin server
    name: springboot-service

logging:
  level:
    root: INFO
  pattern:
    # Note: Logs don't appear to have any correlation fields assigned.
    level: "[%X{user_name}] [%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n"